package com.vx.test.entity;

import java.util.Date;

public class AmzFbaShipmentReports {
    /**
     * 
     */
    private Long id;

    /**
     * 
     */
    private String seller;

    /**
     * 
     */
    private Date shipmentDate;

    /**
     * 出库时间，原始值
     */
    private String shipmentUtcDate;

    /**
     * 
     */
    private String sku;

    /**
     * 
     */
    private String fnsku;

    /**
     * 
     */
    private String asin;

    /**
     * 
     */
    private String fulfillmentCenterId;

    /**
     * 
     */
    private Integer quantity;

    /**
     * 亚马逊订单号
     */
    private String amazonOrderId;

    /**
     * 原始订单号
     */
    private String sellerOrderId;

    /**
     * 
     */
    private String currency;

    /**
     * 
     */
    private Float itemPricePerUnit;

    /**
     * 
     */
    private Float shippingPrice;

    /**
     * 
     */
    private Float giftWrapPrice;

    /**
     * 
     */
    private String shipCity;

    /**
     * 
     */
    private String shipState;

    /**
     * 
     */
    private String shipPostalCode;

    /**
     * 
     */
    private String reportId;

    /**
     * 
     */
    private String marketplaces;

    /**
     * 
     */
    private Date createTime;

    /**
     * 
     */
    private Date updateTime;

    /**
     * 
     */
    private String transferNumber;

    /**
     * 
     */
    private String outbound;

    /**
     * 0未校验，1已校验但未通过，2已校验通过
     */
    private Byte checkStatus;

    /**
     * 亚马逊sku
     */
    private String amzSku;

    /**
     * 是否已匹配msku
     */
    private Boolean mskuMatched;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.id
     *
     * @return the value of amz_fba_shipment_reports.id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.id
     *
     * @param id the value for amz_fba_shipment_reports.id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.seller
     *
     * @return the value of amz_fba_shipment_reports.seller
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getSeller() {
        return seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.seller
     *
     * @param seller the value for amz_fba_shipment_reports.seller
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setSeller(String seller) {
        this.seller = seller == null ? null : seller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.shipment_date
     *
     * @return the value of amz_fba_shipment_reports.shipment_date
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Date getShipmentDate() {
        return shipmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.shipment_date
     *
     * @param shipmentDate the value for amz_fba_shipment_reports.shipment_date
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setShipmentDate(Date shipmentDate) {
        this.shipmentDate = shipmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.shipment_utc_date
     *
     * @return the value of amz_fba_shipment_reports.shipment_utc_date
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getShipmentUtcDate() {
        return shipmentUtcDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.shipment_utc_date
     *
     * @param shipmentUtcDate the value for amz_fba_shipment_reports.shipment_utc_date
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setShipmentUtcDate(String shipmentUtcDate) {
        this.shipmentUtcDate = shipmentUtcDate == null ? null : shipmentUtcDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.sku
     *
     * @return the value of amz_fba_shipment_reports.sku
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.sku
     *
     * @param sku the value for amz_fba_shipment_reports.sku
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.fnsku
     *
     * @return the value of amz_fba_shipment_reports.fnsku
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getFnsku() {
        return fnsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.fnsku
     *
     * @param fnsku the value for amz_fba_shipment_reports.fnsku
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setFnsku(String fnsku) {
        this.fnsku = fnsku == null ? null : fnsku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.asin
     *
     * @return the value of amz_fba_shipment_reports.asin
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getAsin() {
        return asin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.asin
     *
     * @param asin the value for amz_fba_shipment_reports.asin
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setAsin(String asin) {
        this.asin = asin == null ? null : asin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.fulfillment_center_id
     *
     * @return the value of amz_fba_shipment_reports.fulfillment_center_id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getFulfillmentCenterId() {
        return fulfillmentCenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.fulfillment_center_id
     *
     * @param fulfillmentCenterId the value for amz_fba_shipment_reports.fulfillment_center_id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setFulfillmentCenterId(String fulfillmentCenterId) {
        this.fulfillmentCenterId = fulfillmentCenterId == null ? null : fulfillmentCenterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.quantity
     *
     * @return the value of amz_fba_shipment_reports.quantity
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.quantity
     *
     * @param quantity the value for amz_fba_shipment_reports.quantity
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.amazon_order_id
     *
     * @return the value of amz_fba_shipment_reports.amazon_order_id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getAmazonOrderId() {
        return amazonOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.amazon_order_id
     *
     * @param amazonOrderId the value for amz_fba_shipment_reports.amazon_order_id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setAmazonOrderId(String amazonOrderId) {
        this.amazonOrderId = amazonOrderId == null ? null : amazonOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.seller_order_id
     *
     * @return the value of amz_fba_shipment_reports.seller_order_id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getSellerOrderId() {
        return sellerOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.seller_order_id
     *
     * @param sellerOrderId the value for amz_fba_shipment_reports.seller_order_id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setSellerOrderId(String sellerOrderId) {
        this.sellerOrderId = sellerOrderId == null ? null : sellerOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.currency
     *
     * @return the value of amz_fba_shipment_reports.currency
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.currency
     *
     * @param currency the value for amz_fba_shipment_reports.currency
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.item_price_per_unit
     *
     * @return the value of amz_fba_shipment_reports.item_price_per_unit
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Float getItemPricePerUnit() {
        return itemPricePerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.item_price_per_unit
     *
     * @param itemPricePerUnit the value for amz_fba_shipment_reports.item_price_per_unit
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setItemPricePerUnit(Float itemPricePerUnit) {
        this.itemPricePerUnit = itemPricePerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.shipping_price
     *
     * @return the value of amz_fba_shipment_reports.shipping_price
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Float getShippingPrice() {
        return shippingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.shipping_price
     *
     * @param shippingPrice the value for amz_fba_shipment_reports.shipping_price
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setShippingPrice(Float shippingPrice) {
        this.shippingPrice = shippingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.gift_wrap_price
     *
     * @return the value of amz_fba_shipment_reports.gift_wrap_price
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Float getGiftWrapPrice() {
        return giftWrapPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.gift_wrap_price
     *
     * @param giftWrapPrice the value for amz_fba_shipment_reports.gift_wrap_price
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setGiftWrapPrice(Float giftWrapPrice) {
        this.giftWrapPrice = giftWrapPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.ship_city
     *
     * @return the value of amz_fba_shipment_reports.ship_city
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getShipCity() {
        return shipCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.ship_city
     *
     * @param shipCity the value for amz_fba_shipment_reports.ship_city
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setShipCity(String shipCity) {
        this.shipCity = shipCity == null ? null : shipCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.ship_state
     *
     * @return the value of amz_fba_shipment_reports.ship_state
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getShipState() {
        return shipState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.ship_state
     *
     * @param shipState the value for amz_fba_shipment_reports.ship_state
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setShipState(String shipState) {
        this.shipState = shipState == null ? null : shipState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.ship_postal_code
     *
     * @return the value of amz_fba_shipment_reports.ship_postal_code
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getShipPostalCode() {
        return shipPostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.ship_postal_code
     *
     * @param shipPostalCode the value for amz_fba_shipment_reports.ship_postal_code
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setShipPostalCode(String shipPostalCode) {
        this.shipPostalCode = shipPostalCode == null ? null : shipPostalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.report_id
     *
     * @return the value of amz_fba_shipment_reports.report_id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.report_id
     *
     * @param reportId the value for amz_fba_shipment_reports.report_id
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.marketplaces
     *
     * @return the value of amz_fba_shipment_reports.marketplaces
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getMarketplaces() {
        return marketplaces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.marketplaces
     *
     * @param marketplaces the value for amz_fba_shipment_reports.marketplaces
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setMarketplaces(String marketplaces) {
        this.marketplaces = marketplaces == null ? null : marketplaces.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.create_time
     *
     * @return the value of amz_fba_shipment_reports.create_time
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.create_time
     *
     * @param createTime the value for amz_fba_shipment_reports.create_time
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.update_time
     *
     * @return the value of amz_fba_shipment_reports.update_time
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.update_time
     *
     * @param updateTime the value for amz_fba_shipment_reports.update_time
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.transfer_number
     *
     * @return the value of amz_fba_shipment_reports.transfer_number
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getTransferNumber() {
        return transferNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.transfer_number
     *
     * @param transferNumber the value for amz_fba_shipment_reports.transfer_number
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setTransferNumber(String transferNumber) {
        this.transferNumber = transferNumber == null ? null : transferNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.outbound
     *
     * @return the value of amz_fba_shipment_reports.outbound
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getOutbound() {
        return outbound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.outbound
     *
     * @param outbound the value for amz_fba_shipment_reports.outbound
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setOutbound(String outbound) {
        this.outbound = outbound == null ? null : outbound.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.check_status
     *
     * @return the value of amz_fba_shipment_reports.check_status
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Byte getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.check_status
     *
     * @param checkStatus the value for amz_fba_shipment_reports.check_status
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setCheckStatus(Byte checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.amz_sku
     *
     * @return the value of amz_fba_shipment_reports.amz_sku
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public String getAmzSku() {
        return amzSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.amz_sku
     *
     * @param amzSku the value for amz_fba_shipment_reports.amz_sku
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setAmzSku(String amzSku) {
        this.amzSku = amzSku == null ? null : amzSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amz_fba_shipment_reports.msku_matched
     *
     * @return the value of amz_fba_shipment_reports.msku_matched
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public Boolean getMskuMatched() {
        return mskuMatched;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amz_fba_shipment_reports.msku_matched
     *
     * @param mskuMatched the value for amz_fba_shipment_reports.msku_matched
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    public void setMskuMatched(Boolean mskuMatched) {
        this.mskuMatched = mskuMatched;
    }
}