package com.vx.test.repository;

import com.vx.test.entity.AmzFbaShipmentReports;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Pageable;

public interface AmzFbaShipmentReportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    int insert(AmzFbaShipmentReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    int insertSelective(AmzFbaShipmentReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    AmzFbaShipmentReports selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    int updateByPrimaryKeySelective(AmzFbaShipmentReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    int updateByPrimaryKey(AmzFbaShipmentReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    AmzFbaShipmentReports selectOne(AmzFbaShipmentReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    List<AmzFbaShipmentReports> selectList(AmzFbaShipmentReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    List<AmzFbaShipmentReports> selectPage(@Param("record") AmzFbaShipmentReports record, @Param("pageable") Pageable pageable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amz_fba_shipment_reports
     *
     * @mbg.generated Fri Jun 03 21:02:59 CST 2022
     */
    int updateByPrimaryKeySelectiveLock(AmzFbaShipmentReports record);
}